### PR TITLE
Add note on choosing between Datadog api and Dogstatsd.

### PR DESCRIPTION
**Pull request by fitzoh**
Sourced from @jkschneider 's comments in slack, conversation starts [here](https://micrometer-metrics.slack.com/archives/C662HUJC9/p1535053619000100).

### CODE REVIEW

**Comment by ledor473** [comment]
It seems that Slack history has been lost... @jkschneider @fitzoh @shakuzen do you remember what was making the API approach far more efficient?

**Comment by shakuzen** [comment]
The StatsD approach requires publishing each measurement out of process to the StatsD daemon in approximately real time, whereas the API publishes once per step interval per time series. If you increment a counter 100 times per second, you need to publish 100 statsd lines per second for it. If you are using the API, you publish 1 time series per step interval for that counter regardless of how many times it is incremented during the step.

**Comment by ledor473** [comment]
@shakuzen thanks for the clarification!

 I do see a `step` configuration on the StatsdMeterRegistry that's being used on Timer and DistributionSummary, so I assume the above statement is mostly for Counter and Gauge?

**Comment by shakuzen** [comment]
No, my statement is for everything except gauges. Gauges are polled at the configured `pollingFrequency`. Other things, including Timer and DistributionSummary, publish a statsd line per recording. See, for example, `StatsdTimer`: https://github.com/micrometer-metrics/micrometer/blob/508a7328e6574347a7f9d99a85383f50801a6355/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdTimer.java#L57

The `step` for StatsdMeterRegistry is used for time windowing on things like a Timer or DistributionSummary max, which actually don't get published to statsd because statsd calculates max itself from the individual recordings sent to it.

**Comment by ledor473** [comment]
Interesting! I'll take a look at all that.
Thanks so much

**Comment by shakuzen** [comment]
You can [turn on statsd logging](https://github.com/statsd/statsd#debugging) or use something like netcat to listen on a UDP/TCP port to see precisely what gets published to statsd when, also.

**Pull request merged**
