### PR TITLE
Polish

### PR DESCRIPTION
**Pull request by izeye**
This PR fixes some typos and polishes trivial stuff.

### CODE REVIEW

**Comment by jkschneider** [comment]
Thanks again!

**Comment by jkschneider** [comment]
Your changes are live on the site ;)

**Comment by izeye** [comment]
@jkschneider Thanks for the quick feedback!

> Your changes are live on the site ;)

Do you mean the changes have been applied to the published reference documentation?

**Comment by izeye** [comment]
@jkschneider I can't see the changes from https://micrometer.io/docs/concepts

Am I missing something? 😅

**Comment by jkschneider** [comment]
Just need to force a browser refresh. I see the changes live right now.

**Comment by izeye** [comment]
@jkschneider Ah, sorry! I confirmed the changes now 👍

**Pull request merged**
