### PR TITLE
API -> DSD as default configuration

### PR DESCRIPTION
**Pull request by jeremy-lq**
Updating the default configuration to DogStatsD, which is more efficient and has other advantages.

### CODE REVIEW

**Comment by rehevkor5** [comment]
It's worth noting that @jeremy-lq is a member of the Datadog org.

Here's the context for the existing advice on that page: https://github.com/micrometer-metrics/micrometer-docs/pull/93#issuecomment-915734481

> The StatsD approach requires publishing each measurement out of process to the StatsD daemon in approximately real time, whereas the API publishes once per step interval per time series. If you increment a counter 100 times per second, you need to publish 100 statsd lines per second for it. If you are using the API, you publish 1 time series per step interval for that counter regardless of how many times it is incremented during the step.

@jeremy-lq is that information correct/incorrect/misleading/incomplete?

**Comment by platinummonkey** [comment]
👋  howdy :) while that's true in the default case we have this wonderful doc on high throughput metrics with multi-language (including java) support https://docs.datadoghq.com/developers/dogstatsd/high_throughput/ see the `java` tab for an example. In addition communicating over UDS can potentially offer additional performance improvements.

**Comment by platinummonkey** [comment]
The [agent already aggregates and reduces APIs](https://docs.datadoghq.com/developers/dogstatsd/data_aggregation/). It also has additional logic to ensure data is delivered and properly retried to our intake systems. In addition agents can be configured to dual report metrics to multiple tenant instances if the user desires without making sweeping code changes.

This isn't to say you couldn't still aggregate client side and push to the agent directly. [This guide](https://docs.datadoghq.com/developers/dogstatsd/data_aggregation/#aggregation-rules-per-metric-type) gives details on how the aggregation is performed to ensure compatibility.

Also the agent intake has elevated limits when accepting payloads that do not count against User/Automation queries on the general APIs currently being consumed by the API Method option.

**Comment by jonatan-ivanov** [comment]
@platinummonkey 
>The agent already aggregates and reduces APIs.

I guess that helps from the backend perspective but if I understand it correctly it helps nothing to the client (user's app), they still need to send every data point separately so I think I still not get how publishing each measurement can be more efficient than sending an aggregate from the client's/user's/Micrometer's perspective.

This is basically where I would like to see some explanation:
>The DogStatsD approach is far more efficient, especially if you have a high volume of metrics.

Since to me it seems that StatsD is far less efficient, especially if you have a high volume of metrics (please notice that Micrometer does not use the DataDog `StatsDClient`).

**Comment by platinummonkey** [comment]
It seems these performance tests are against micrometer's own implementations of aggregation via custom API calls, vs it's own implementation of statsd line protocol to mimic some but not all Datadog's official statsd client.

> please notice that Micrometer does not use the DataDog StatsDClient

Since this is a datadog stastd plugin I'm confused why it wouldn't use the datadog official Datadog java statsd client?  The docs seem to imply multiple re-inventions of the official implementation details but misses on aggregation? The official Datadog statsd client has [client side aggregation that is simple to enable](https://docs.datadoghq.com/developers/dogstatsd/high_throughput/#client-side-aggregation). That aggregated client mode sends an aggregated response the the local agent, not each individual point submission.  The agent itself is quite lightweight even under heavy data load, and already installed on the affected customers machines to benefit from other observability data. 

>  not needed on the classpath for this to work, as Micrometer uses its own implementation
Why was this needed? What was missing or didn't work?

The agent then does further aggregation where appropriate and uses an optimized submission payload against intake endpoints, including retry and backoff behavior that results in stability of points, logs, traces and profiles being received. The agent itself is very lightweight and benefits by also providing tracing, jvm profiling, logging and a host of other features.

It seems micrometer is trying to reinvent this logic, but only for metrics. At high load it is now impacting users ability to use Datadog due to the non optimized intake submission, and infinite retry patterns for updating metric metadata on 404, and no back off on 429 responses. So now not only will they not get their data, they won’t be able to find out why either without intervention from Datadog Support.

**Comment by rehevkor5** [comment]
> they still need to send every data point separately

At the risk of repeating myself, why not change `StatsdCounter` into a `StatsdPollable` so it reports the count delta to its sink only when polled, rather than on every call to increment()? I guess I will open an issue in the main repo to suggest that.

> Btw JVM agents do not work in native images.

That is a good point. But I am not sure if we are all talking about the same "agent". Sadly, there is a Datadog JVM agent described here https://docs.datadoghq.com/tracing/setup_overview/setup/java/?tab=containers , but there is also the "Datadog Agent". The terminology is indeed confusing. In general, if you are using Micrometer to send metrics to Datadog via statsd, then you are sending it to the Datadog Agent which is running as a separate process. If you are using the Datadog JVM agent, you definitely must also run the Datadog Agent.

Datadog's documentation is somewhat inconsistent about how to send metrics from Java. In this page it says to expose metrics via JMX: https://docs.datadoghq.com/integrations/java/?tab=host However in these pages https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent#pagetitle for whatever reason they recommend dogstatsd instead. Also interesting to not that the page listing libraries https://docs.datadoghq.com/developers/community/libraries/ does not include Micrometer :)

> Closing this issue since what its description states does not seem to be true

Maybe we can agree that it is debatable, as I think this thread proves. Let me add some flavor about the earlier statement that "At high load it is now impacting users ability to use Datadog". Yes, with the current implementation there are some good things about reporting directly to the API. If you are a small user with a low rate of API requests, you probably won't have any problems. But, on the other hand, if you are a big user of Datadog with many different apps all following the advice on this page and sending Datadog metrics to the API, you may certainly end up with problems and it will require a lot of work across your apps to fix them. You may start getting back 429 responses from API queries that were previously working even for reads, not only for sending metrics. For whatever reason, those might not even have a response body or rate limiting headers, so you can't do proper backoff. Also, the rate limiting appears to be at the account level not the API Key level or App Key level. Therefore, even if one app is sending too rapidly, that could break all your other well-behaved apps.

Sadly, I see no information about that on https://docs.datadoghq.com/api/latest/metrics/#submit-metrics (linked from https://docs.datadoghq.com/metrics/custom_metrics/ ), and the info on https://docs.datadoghq.com/api/latest/rate-limits/ does not indicate that metrics submission rate limit can impact clients that are not sending metrics.

Now, obviously these are all issues which should be dealt with better on the Datadog side. But for users of Micrometer, we should try to give them responsible advice based on the info we have available. Personally, I would not in good conscience recommend to a friend or coworker that everyone use API based reporting simply because it might be more efficient.

Therefore, perhaps a more nuanced explanation is needed, so that we can agree on a change which is helpful to the community? Specifically, we could mention that while there are some efficiency benefits in using API based reporting, that you need to consider the possibility of reaching account-level API rate limiting if you are reporting metrics directly to the API instead of via statsd+Datadog Agent.

**Comment by aptituz** [comment]
I can't contribute to the efficiency debate here (their seem to be reasonable arguments on both sides), but as a user, who recently ran into trouble due to using micrometer in the default configuration and some unfortunate circumstances, I would like to add two cents about the documentation aspect.

With respect to the sentence "The API approach is far more efficient if you need to choose between the two.": it would be nice if the docs could be a bit more elaborate here. For example, from the comments above I understand that the efficiency concern is mainly about "high volume of metrics" situations (because of IPC involved and metrics not being batched) and it seems that this would be a helpful information for tradeoff-decisions. Even better if it could be quantified somehow what high volume means and what problems a user can expect.

(On a slightly related side-note: since the dogstatsd-approach supports distribution metrics and the API approach currently doesn't, its pretty easy to get into the situation having to chose between the two :)).

**Comment by platinummonkey** [comment]
I've submitted https://github.com/micrometer-metrics/micrometer/pull/3329 to address the technical implementation. Will circle back on the docs once that is resolved.

**Comment by platinummonkey** [comment]
Hey folks, here we are over a year later 🎂. The https://github.com/micrometer-metrics/micrometer/pull/3329 PR is still open and looking for reviews. 


We're continuing to see many customers run into issues of infinite spam from the API-driven integration over the agent-based stats reporting.

As an additional note: It appears the API-driven approach seems to be lossy under these circumstances :warning: Also in some cases customers have limited NAT gateways which results in much of their application experience being blocked at rate limits are reached :warning:

**Comment by platinummonkey** [comment]
See https://github.com/micrometer-metrics/micrometer/pull/4283

**Comment by jonatan-ivanov** [comment]
Let me close this since we moved the docs to their respective projects and we are still planning to look into using Dogstatsd in the `DatadogMeterRegistry` sometimes later (as far as I remember there were some issues in that implementation that should be fixed). After that we can call that out in our docs.

**Comment by platinummonkey** [comment]
> Let me close this since we moved the docs to their respective projects and we are still planning to look into using Dogstatsd in the `DatadogMeterRegistry` sometimes later (as far as I remember there were some issues in that implementation that should be fixed). After that we can call that out in our docs.

Given that perfectly compatible Prometheus and OTel plugins exist in micrometer as alternatives this documentation link ( https://docs.datadoghq.com/metrics/guide/micrometer/ ) will remain the source of truth for Datadog and will be our first set of guided instructions for anyone running into the documented issues linked here.

The suggested PRs haven’t been accepted and are now closed but not solved.

**Comment by izeye** [comment]
I created https://github.com/micrometer-metrics/micrometer/pull/4871 to try to include a note for the Datadog API rate limit problem that has been discussed here.

**Pull request closed without merging**
