### PR TITLE
Document health metrics sample configuration for Spring Boot 2.2

### PR DESCRIPTION
**Pull request by izeye**
This PR documents health metrics sample configuration for Spring Boot 2.2.

See https://github.com/spring-projects/spring-boot/issues/18194

### CODE REVIEW

**Comment by izeye** [comment]
I missed https://github.com/spring-projects/spring-boot/issues/18329. It seems to supersede this.

**Comment by shakuzen** [comment]
> I missed [spring-projects/spring-boot#18329](https://github.com/spring-projects/spring-boot/issues/18329). It seems to supersede this.

Indeed. I would rather defer to that than keep updating the documentation here for changes in Spring Boot.

**Comment by philwebb** [comment]
The Boot issue is now fixed and this issue has been superseded by #2023

**Comment by izeye** [comment]
@philwebb Thanks, much nicer 👍

**Pull request closed without merging**
